DROP TABLE IF EXISTS votes;

CREATE TABLE votes (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  review_id INTEGER REFERENCES reviews(id) ON DELETE CASCADE,
  voteStatus BOOLEAN DEFAULT TRUE
);